server:
  port: 8090

spring:
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    driverClassName: com.mysql.cj.jdbc.Driver  # MySQL
    # mysql????
    # url: jdbc:mysql://localhost:3306/puzzle_day?serverTimezone=GMT%2B0&&useUnicode=true&characterEncoding=UTF-8&useSSL=false
    url: jdbc:mysql://localhost:3306/class_schedule?serverTimezone=GMT%2B8&&useUnicode=true&characterEncoding=UTF-8&useSSL=false
    username: classschedule
    password: 123456

# mybatis配置
mybatis:
  configuration: # mybatis-plus配置控制台打印完整带参数SQL语句
#    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
    map-underscore-to-camel-case: true    # 驼峰转换 从数据库列名到Java属性驼峰命名的类似映射
  #  mapper-locations: classpath:/mapper/*.xml   # 引入mybatis-plus-boot-starter包，需要配置路径
  type-aliases-package: com.example.classschedule.data.entity
  mapperLocations: classpath:mapper/*.xml

fx:
  # 导入、导出等文件路径
  profile: C:/Users/86181/Desktop/study/福新小学/class-schedule/doc

#
## springdoc-openapi项目配置
#springdoc:
#  swagger-ui:
#    #自定义swagger前端请求路径,输入http:localhost:8090/swagger-ui.html会自动重定向到swagger页面
#    path: /swagger-ui.html
#    tags-sorter: alpha
#    operations-sorter: alpha
#  api-docs:
#    path: /v3/api-docs    #swagger后端请求地址
#    enabled: true   #是否开启文档功能
#  group-configs:
#    - group: 'default'   #分组名称
#      paths-to-match: '/**'   #配置需要匹配的路径,默认为/**
#      packages-to-scan: com.example.classschedule.controller    #配置要扫描包的路径,一般配置到启动类所在的包名
#
## knife4j的增强配置，不需要增强可以不配(建议配置一下)
#knife4j:
#  enable: true    #开启knife4j,无需添加@EnableKnife4j注解
#  setting:
#    language: zh_cn   #中文